// web/src/routes/starter/ProgressBar.svelte
<script lang="ts">
    
    interface Props {
        text: string;
        progress: number;
    }
    
    let { text, progress }: Props = $props();

</script>

<div data-tauri-drag-region class="w-full h-8 overflow-hidden relative rounded-md bg-gray-700">
    <div
        data-tauri-drag-region
        class="h-full bg-blue-500/50 origin-left transform transition-transform duration-300"
        style="transform: scaleX({progress})"
    ></div>
    <div data-tauri-drag-region class="absolute inset-0 flex items-center justify-center text-white text-sm select-none">
        {text}
    </div>
</div>

// src/components/Session/ProgressBar.tsx
import React from "react";

interface Props {
    value: number;
    onCancel: () => void;
}

const ProgressBar: React.FC<Props> = ({ value, onCancel }) => {
    return (
        <div className="flex items-center justify-center my-4 w-full">
            <button
                onClick={onCancel}
                className="text-gray-300 hover:text-white p-2"
            >
                ✕
            </button>
            <div
                className="w-3/4 bg-gray-700 h-4 rounded-full overflow-hidden ml-2"
                data-value={`${value}%`}
            >
                <div
                    className="bg-blue-500 h-4 transition-all duration-300"
                    style={{ width: `${value}%` }}
                ></div>
            </div>
        </div>
    );
};

export default ProgressBar;
